import Link from "next/link"
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>

        <div><h1>Covid-19 tracker </h1></div>
        <div>
            <p className={styles.p}>Cases : <span className={styles.span}>{data.cases}</span></p>
            <p className={styles.p}>todayCases : <span className={styles.span}>{data.todayCases}</span></p>
            <p className={styles.p}>todayDeaths : <span className={styles.span}>{data.todayDeaths}</span></p>
            <p className={styles.p}>recovered : <span className={styles.span}>{data.recovered}</span></p>
            <p className={styles.p}>todayRecovered : <span className={styles.span}>{data.todayRecovered}</span></p>
            <p className={styles.p}>active : <span className={styles.span}>{data.active}</span></p>
            <p className={styles.p}>critical : <span className={styles.span}>{data.critical}</span></p>
            <p className={styles.p}>deathsPerOneMillion : <span className={styles.span}>{data.deathsPerOneMillion}</span></p>
            <p className={styles.p}>casesPerOneMillion : <span className={styles.span}>{data.casesPerOneMillion}</span></p>
        </div>
        
          <button className={styles.btn}><Link  href="/country"> Search </Link></button>

      </div>

    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch('https://disease.sh/v3/covid-19/all')
  const data = await res.json()

  return {
    props: {
      data,
    },
  }
}





{/* https://disease.sh/v3/covid-19/all */ }
